// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SmartParking.Domain.Entities;
using SmartParking.Domain.Interfaces;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq.Expressions;
using System.Security.Claims;

#nullable enable

namespace SmartParking.Infrastructure.Data;

public partial class SmartParkingDBContext : Microsoft.EntityFrameworkCore.DbContext
{
    private readonly IHttpContextAccessor? _httpContextAccessor;

    public SmartParkingDBContext()
    {
    }

    public SmartParkingDBContext(
        DbContextOptions<SmartParkingDBContext> options,
        IHttpContextAccessor? httpContextAccessor = null)
        : base(options)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public virtual DbSet<Booking> Bookings { get; set; }
    
    public virtual DbSet<EmailOtp> EmailOtps { get; set; }

    public virtual DbSet<ParkingLot> ParkingLots { get; set; }

    public virtual DbSet<OwnerUpgradeRequest> OwnerUpgradeRequests { get; set; }

    public virtual DbSet<OwnerBankAccount> OwnerBankAccounts { get; set; }

    public virtual DbSet<ParkingLocation> ParkingLocations { get; set; }

    public virtual DbSet<PaymentLog> PaymentLogs { get; set; }

    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAuth> UserAuths { get; set; }

    public virtual DbSet<UserToken> UserTokens { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string? connectionString = config.GetConnectionString(connectionStringName);
        return connectionString ?? throw new InvalidOperationException($"Connection string '{connectionStringName}' not found in appsettings.json");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // NOTE: Connection string is configured via DI in ServiceCollectionExtensions.cs
        // Only configure here if not already configured (for migrations/design-time)
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"))
                .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
        }
    }
 
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951AEDA4381824");

            entity.Property(e => e.BookingId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BookingTime)
                .IsRequired()
                .HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.StartTime).IsRequired();
            entity.Property(e => e.EndTime).IsRequired();
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TotalAmount)
                .IsRequired()
                .HasColumnType("decimal(18, 2)")
                .HasDefaultValue(0);
            entity.Property(e => e.CreatedAt)
                .IsRequired()
                .HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UpdatedAt);
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false);
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.IsDeleted)
                .HasDatabaseName("IX_Bookings_IsDeleted")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => new { e.UserId, e.IsDeleted })
                .HasDatabaseName("IX_Bookings_UserId_IsDeleted")
                .HasFilter("[IsDeleted] = 0");

            // Relationships
            entity.HasOne(d => d.ParkingLot).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.ParkingLotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__Parkin__6E01572D");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__UserId__6D0D32F4");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Bookings__VehicleId__ABCD1234");
                
            // Global query filter for soft delete
            entity.HasQueryFilter(e => !e.IsDeleted);
        });

        modelBuilder.Entity<EmailOtp>(entity =>
        {
            entity.HasKey(e => e.OtpId).HasName("PK__EmailOtp__OtpId");

            entity.Property(e => e.OtpId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.OtpCode)
                .IsRequired()
                .HasMaxLength(6);
            entity.Property(e => e.OtpType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Registration");
            entity.Property(e => e.ExpiredAt).IsRequired();
            entity.Property(e => e.IsUsed).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.TemporaryFullName).HasMaxLength(255);
            entity.Property(e => e.TemporaryPhone).HasMaxLength(20);

            entity.HasIndex(e => new { e.Email, e.IsUsed })
                .HasDatabaseName("IX_EmailOtps_Email_IsUsed")
                .HasFilter("[IsUsed] = 0");

            entity.HasIndex(e => e.ExpiredAt)
                .HasDatabaseName("IX_EmailOtps_ExpiredAt")
                .HasFilter("[IsUsed] = 0");
            
            entity.HasIndex(e => new { e.OtpType, e.Email, e.IsUsed })
                .HasDatabaseName("IX_EmailOtps_OtpType_Email_IsUsed")
                .HasFilter("[IsUsed] = 0");
        });

        modelBuilder.Entity<ParkingLot>(entity =>
        {
            entity.HasKey(e => e.ParkingLotId).HasName("PK__ParkingL__6F271E8943112B49");

            entity.Property(e => e.ParkingLotId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TotalCapacity).IsRequired();
            entity.Property(e => e.CurrentOccupancy)
                .HasDefaultValue(0);
            entity.Property(e => e.PricePerHour)
                .HasColumnType("decimal(10, 2)")
                .IsRequired();
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Active");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UpdatedAt);
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false);
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.IsDeleted)
                .HasDatabaseName("IX_ParkingLots_IsDeleted")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => e.IsActive)
                .HasDatabaseName("IX_ParkingLots_IsActive");
                
            entity.HasIndex(e => new { e.OwnerId, e.IsDeleted })
                .HasDatabaseName("IX_ParkingLots_OwnerId_IsDeleted")
                .HasFilter("[IsDeleted] = 0");

            // Relationships
            entity.HasOne(d => d.Owner).WithMany(p => p.ParkingLots)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ParkingLo__Owner__6477ECF3");
                
            // Global query filter for soft delete
            entity.HasQueryFilter(e => !e.IsDeleted);
        });

        modelBuilder.Entity<PaymentLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__PaymentL__5E54864846821D57");

            entity.Property(e => e.LogId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Payment).WithMany(p => p.PaymentLogs)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PaymentLo__Payme__7B5B524B");
        });

        modelBuilder.Entity<PaymentTransaction>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__PaymentT__9B556A38C863861B");

            entity.Property(e => e.PaymentId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Amount)
                .IsRequired()
                .HasColumnType("decimal(12, 2)");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("VNPay");
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.VnpTxnRef)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.VnpTransactionNo).HasMaxLength(100);
            entity.Property(e => e.VnpResponseCode).HasMaxLength(10);
            entity.Property(e => e.VnpBankCode).HasMaxLength(50);
            entity.Property(e => e.VnpCardType).HasMaxLength(50);
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.RefundReason).HasMaxLength(500);
            entity.Property(e => e.Metadata).HasMaxLength(4000);
            entity.Property(e => e.CreatedAt)
                .IsRequired()
                .HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UpdatedAt);
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false);

            // Indexes
            entity.HasIndex(e => e.VnpTxnRef)
                .IsUnique()
                .HasDatabaseName("IX_PaymentTransactions_VnpTxnRef")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => e.IsDeleted)
                .HasDatabaseName("IX_PaymentTransactions_IsDeleted")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => new { e.UserId, e.IsDeleted })
                .HasDatabaseName("IX_PaymentTransactions_UserId_IsDeleted")
                .HasFilter("[IsDeleted] = 0");

            // Relationships
            entity.HasOne(d => d.Booking).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PaymentTr__Booki__75A278F5");

            entity.HasOne(d => d.User).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PaymentTr__UserI__76969D2E");
                
            // Global query filter for soft delete
            entity.HasQueryFilter(e => !e.IsDeleted);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1A59DEC7BF");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B616059A79E52").IsUnique();

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C78F84F6E");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534F8873709").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.EmailConfirmed).HasDefaultValue(false);
            entity.Property(e => e.Phone).HasMaxLength(20);

            entity.HasIndex(e => e.EmailConfirmed)
                .HasDatabaseName("IX_Users_EmailConfirmed");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleId__5165187F");
        });

        modelBuilder.Entity<UserAuth>(entity =>
        {
            entity.HasKey(e => e.AuthId).HasName("PK__UserAuth__12C15DD3AE8D1637");

            entity.ToTable("UserAuth");

            entity.HasIndex(e => new { e.Provider, e.ProviderUserId }, "UQ_Provider").IsUnique();

            entity.Property(e => e.AuthId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.PasswordHash).HasMaxLength(255);
            entity.Property(e => e.Provider).HasMaxLength(20);
            entity.Property(e => e.ProviderUserId).HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.UserAuths)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserAuth__UserId__5812160E");
        });

        modelBuilder.Entity<UserToken>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__UserToke__658FEEEAA5253A9D");

            entity.Property(e => e.TokenId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);
            entity.Property(e => e.RefreshToken)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.UserTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserToken__UserI__5DCAEF64");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicles__476B54B2A1234567");

            entity.HasIndex(e => e.LicensePlate, "UQ_LicensePlate").IsUnique();

            entity.Property(e => e.VehicleId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.LicensePlate)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Brand).HasMaxLength(50);
            entity.Property(e => e.Model).HasMaxLength(50);
            entity.Property(e => e.Color).HasMaxLength(30);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Vehicles__UserId__12345678");
        });

        modelBuilder.Entity<ParkingLocation>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK_ParkingLocations");

            entity.Property(e => e.LocationId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ParkingLotId).IsRequired();
            entity.Property(e => e.Latitude)
                .IsRequired()
                .HasColumnType("decimal(10, 7)");
            entity.Property(e => e.Longitude)
                .IsRequired()
                .HasColumnType("decimal(10, 7)");
            entity.Property(e => e.Province).HasMaxLength(100);
            entity.Property(e => e.District).HasMaxLength(100);
            entity.Property(e => e.Ward).HasMaxLength(100);
            entity.Property(e => e.Street).HasMaxLength(255);
            entity.Property(e => e.Area).HasMaxLength(255);
            entity.Property(e => e.FullAddress).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .IsRequired()
                .HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UpdatedAt);
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false);

            // Check constraints for valid coordinates
            entity.ToTable(t =>
            {
                t.HasCheckConstraint("CK_ParkingLocations_Latitude", "[Latitude] >= -90 AND [Latitude] <= 90");
                t.HasCheckConstraint("CK_ParkingLocations_Longitude", "[Longitude] >= -180 AND [Longitude] <= 180");
            });

            // Indexes
            entity.HasIndex(e => e.IsDeleted)
                .HasDatabaseName("IX_ParkingLocations_IsDeleted")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => new { e.Latitude, e.Longitude })
                .HasDatabaseName("IX_ParkingLocations_Lat_Lng")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => new { e.Province, e.District })
                .HasDatabaseName("IX_ParkingLocations_Province_District")
                .HasFilter("[IsDeleted] = 0");
                
            entity.HasIndex(e => e.ParkingLotId)
                .IsUnique()
                .HasDatabaseName("UQ_ParkingLocations_ParkingLotId")
                .HasFilter("[IsDeleted] = 0");

            // Relationships
            entity.HasOne(d => d.ParkingLot).WithMany()
                .HasForeignKey(d => d.ParkingLotId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ParkingLocations_ParkingLots");
                
            // Global query filter for soft delete
            entity.HasQueryFilter(e => !e.IsDeleted);
        });

        modelBuilder.Entity<OwnerUpgradeRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK_OwnerUpgradeRequests");

            entity.Property(e => e.RequestId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.FullNameSnapshot).HasMaxLength(100);
            entity.Property(e => e.EmailSnapshot).HasMaxLength(256);
            entity.Property(e => e.PhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.ParkingLotName).HasMaxLength(100);
            entity.Property(e => e.ParkingLotAddress).HasMaxLength(255);
            entity.Property(e => e.PlanType).HasMaxLength(50);
            entity.Property(e => e.FeeAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.RejectReason).HasMaxLength(500);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasIndex(e => new { e.Status, e.CreatedAt })
                .HasDatabaseName("IX_OwnerUpgradeRequests_Status_CreatedAt");

            entity.HasIndex(e => e.UserId)
                .HasDatabaseName("IX_OwnerUpgradeRequests_UserId");

            entity.HasOne(d => d.User)
                .WithMany(p => p.OwnerUpgradeRequests)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OwnerUpgradeRequests_Users");
        });

        modelBuilder.Entity<OwnerBankAccount>(entity =>
        {
            entity.HasKey(e => e.OwnerBankAccountId).HasName("PK_OwnerBankAccounts");

            entity.Property(e => e.OwnerBankAccountId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BankCode).HasMaxLength(20);
            entity.Property(e => e.BankName).HasMaxLength(100);
            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.AccountHolderName).HasMaxLength(100);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasIndex(e => e.UserId)
                .HasDatabaseName("IX_OwnerBankAccounts_UserId");

            entity.HasIndex(e => new { e.UserId, e.IsDefault })
                .HasDatabaseName("IX_OwnerBankAccounts_UserId_IsDefault");

            entity.HasOne(d => d.User)
                .WithMany(p => p.OwnerBankAccounts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OwnerBankAccounts_Users");
        });

        // Global query filter for soft delete
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            if (typeof(ISoftDeletable).IsAssignableFrom(entityType.ClrType))
            {
                var parameter = Expression.Parameter(entityType.ClrType, "e");
                var property = Expression.Property(parameter, nameof(ISoftDeletable.IsDeleted));
                var filter = Expression.Lambda(Expression.Equal(property, Expression.Constant(false)), parameter);
                
                entityType.SetQueryFilter(filter);
            }
        }

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    /// <summary>
    /// Override SaveChangesAsync to automatically populate audit fields (CreatedBy/UpdatedBy)
    /// and handle soft delete operations.
    /// SECURITY: Gets UserId from HttpContext JWT claims - never trust client input.
    /// </summary>
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var currentUserId = GetCurrentUserId();
        var now = DateTime.UtcNow;

        // Handle auditable entities
        foreach (var entry in ChangeTracker.Entries<IAuditable>())
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    entry.Entity.CreatedAt = now;
                    entry.Entity.CreatedBy = currentUserId;
                    break;

                case EntityState.Modified:
                    entry.Entity.UpdatedAt = now;
                    entry.Entity.UpdatedBy = currentUserId;
                    // Prevent modification of creation fields
                    entry.Property(nameof(IAuditable.CreatedAt)).IsModified = false;
                    entry.Property(nameof(IAuditable.CreatedBy)).IsModified = false;
                    break;
            }
        }

        // Handle soft delete entities
        foreach (var entry in ChangeTracker.Entries<ISoftDeletable>())
        {
            if (entry.State == EntityState.Deleted)
            {
                // Convert hard delete to soft delete
                entry.State = EntityState.Modified;
                entry.Entity.IsDeleted = true;
                entry.Entity.DeletedAt = now;
                entry.Entity.DeletedBy = currentUserId;
            }
        }

        return await base.SaveChangesAsync(cancellationToken);
    }

    /// <summary>
    /// Extracts current user ID from JWT in HTTP context.
    /// Returns null if no user is authenticated (e.g., anonymous endpoints, background jobs).
    /// </summary>
    private Guid? GetCurrentUserId()
    {
        if (_httpContextAccessor?.HttpContext?.User == null)
            return null;

        var userIdClaim = _httpContextAccessor.HttpContext.User.FindFirstValue(JwtRegisteredClaimNames.Sub)
            ?? _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

        return Guid.TryParse(userIdClaim, out var userId) ? userId : null;
    }
}