using SmartParking.Application.Common.Exceptions;
using SmartParking.Application.Common.Helpers;
using SmartParking.Application.Common.Models;
using SmartParking.Application.DTOs.ParkingLot;
using SmartParking.Application.Interfaces.Repositories;
using SmartParking.Application.Interfaces.Services;
using SmartParking.Domain.Constants;
using SmartParking.Domain.Entities;

namespace SmartParking.Application.Services;

public sealed class ParkingLotService : IParkingLotService
{
    private readonly IParkingLotRepository _parkingLotRepository;
    private readonly IUserRepository _userRepository;
    private readonly IRoleRepository _roleRepository;

    public ParkingLotService(
        IParkingLotRepository parkingLotRepository,
        IUserRepository userRepository,
        IRoleRepository roleRepository)
    {
        _parkingLotRepository = parkingLotRepository;
        _userRepository = userRepository;
        _roleRepository = roleRepository;
    }

    public async Task<ParkingLotResponseDto> GetByIdAsync(Guid parkingLotId, CancellationToken ct = default)
    {
        var parkingLot = await _parkingLotRepository.GetByIdAsync(parkingLotId, includeDeleted: false, ct);
        if (parkingLot == null)
        {
            throw new NotFoundException(Messages.ParkingLot.NotFound);
        }

        return MapToResponseDto(parkingLot);
    }

    public async Task<PagedResult<ParkingLotResponseDto>> GetAllAsync(ParkingLotFilterDto filter, CancellationToken ct = default)
    {
        var pagedResult = await _parkingLotRepository.GetAllAsync(
            filter.SearchTerm,
            filter.IsActive,
            filter.Status,
            filter.Page,
            filter.PageSize,
            ct);

        var dtos = pagedResult.Items.Select(MapToResponseDto).ToList();
        
        return new PagedResult<ParkingLotResponseDto>(
            dtos,
            pagedResult.Page,
            pagedResult.PageSize,
            pagedResult.TotalCount);
    }

    public async Task<IEnumerable<ParkingLotResponseDto>> GetMyParkingLotsAsync(Guid ownerId, CancellationToken ct = default)
    {
        var parkingLots = await _parkingLotRepository.GetByOwnerIdAsync(ownerId, includeDeleted: false, ct);
        return parkingLots.Select(MapToResponseDto);
    }

    public async Task<ParkingLotResponseDto> CreateAsync(
        CreateParkingLotDto request,
        Guid ownerId,
        bool isAdmin,
        CancellationToken ct = default)
    {
        // Verify owner exists and has Owner or Admin role
        var owner = await _userRepository.GetByIdAsync(ownerId, ct);
        if (owner == null)
        {
            throw new NotFoundException(Messages.Auth.UserNotFound);
        }

        // Verify user is Owner or Admin
        if (owner.Role.RoleName != AuthConstants.Roles.Owner && 
            owner.Role.RoleName != AuthConstants.Roles.Admin)
        {
            throw new ForbiddenException("Only Owners and Admins can create parking lots");
        }

        var now = DateTime.UtcNow;

        var parkingLot = new ParkingLot
        {
            ParkingLotId = Guid.NewGuid(),
            OwnerId = ownerId,
            Name = request.Name.Trim(),
            Address = request.Address.Trim(),
            TotalCapacity = request.TotalCapacity,
            CurrentOccupancy = 0,
            PricePerHour = request.PricePerHour,
            Latitude = request.Latitude,
            Longitude = request.Longitude,
            ImageUrl = request.ImageUrl,
            Status = isAdmin ? ParkingLotStatus.Approved : ParkingLotStatus.PendingApproval,
            IsActive = isAdmin,
            RejectReason = null,
            CreatedAt = now,
            CreatedBy = ownerId,
            IsDeleted = false
            // RowVersion is auto-generated by SQL Server (ROWVERSION type) - do not set manually
        };

        var created = await _parkingLotRepository.CreateAsync(parkingLot, ct);
        created.Owner = owner; // Set for DTO mapping
        return MapToResponseDto(created);
    }

    public async Task<ParkingLotResponseDto> UpdateAsync(
        Guid parkingLotId, 
        UpdateParkingLotDto request, 
        Guid userId, 
        bool isAdmin,
        CancellationToken ct = default)
    {
        var parkingLot = await _parkingLotRepository.GetByIdAsync(parkingLotId, includeDeleted: false, ct);
        if (parkingLot == null)
        {
            throw new NotFoundException(Messages.ParkingLot.NotFound);
        }

        // SECURITY: Validate ownership or Admin access
        SecurityHelper.ValidateOwnership(parkingLot.OwnerId, userId, isAdmin);

        // Validate capacity cannot be less than current occupancy
        if (request.TotalCapacity < parkingLot.CurrentOccupancy)
        {
            throw new BadRequestException(
                $"Total capacity cannot be less than current occupancy ({parkingLot.CurrentOccupancy})");
        }

        // Update fields
        parkingLot.Name = request.Name.Trim();
        parkingLot.Address = request.Address.Trim();
        parkingLot.TotalCapacity = request.TotalCapacity;
        parkingLot.PricePerHour = request.PricePerHour;
        parkingLot.Latitude = request.Latitude;
        parkingLot.Longitude = request.Longitude;
        parkingLot.ImageUrl = request.ImageUrl ?? parkingLot.ImageUrl;
        parkingLot.IsActive = request.IsActive;
        parkingLot.UpdatedAt = DateTime.UtcNow;
        parkingLot.UpdatedBy = userId;

        await _parkingLotRepository.UpdateAsync(parkingLot, ct);
        return MapToResponseDto(parkingLot);
    }

    public async Task DeleteAsync(Guid parkingLotId, Guid userId, bool isAdmin, CancellationToken ct = default)
    {
        var parkingLot = await _parkingLotRepository.GetByIdAsync(parkingLotId, includeDeleted: false, ct);
        if (parkingLot == null)
        {
            throw new NotFoundException(Messages.ParkingLot.NotFound);
        }

        // SECURITY: Validate ownership or Admin access
        SecurityHelper.ValidateOwnership(parkingLot.OwnerId, userId, isAdmin);

        // Soft delete
        await _parkingLotRepository.SoftDeleteAsync(parkingLotId, userId, ct);
    }

    public async Task<ParkingLotResponseDto> ToggleActiveAsync(Guid parkingLotId, Guid userId, bool isAdmin, CancellationToken ct = default)
    {
        var parkingLot = await _parkingLotRepository.GetByIdAsync(parkingLotId, includeDeleted: false, ct);
        if (parkingLot == null)
        {
            throw new NotFoundException(Messages.ParkingLot.NotFound);
        }

        // SECURITY: Validate ownership or Admin access
        SecurityHelper.ValidateOwnership(parkingLot.OwnerId, userId, isAdmin);

        // Toggle IsActive
        parkingLot.IsActive = !parkingLot.IsActive;
        parkingLot.UpdatedAt = DateTime.UtcNow;
        parkingLot.UpdatedBy = userId;

        await _parkingLotRepository.UpdateAsync(parkingLot, ct);
        return MapToResponseDto(parkingLot);
    }

    public async Task<ParkingLotResponseDto> ApproveAsync(Guid parkingLotId, Guid adminId, CancellationToken ct = default)
    {
        var parkingLot = await _parkingLotRepository.GetByIdAsync(parkingLotId, includeDeleted: false, ct);
        if (parkingLot == null)
        {
            throw new NotFoundException(Messages.ParkingLot.NotFound);
        }

        if (parkingLot.Status != ParkingLotStatus.PendingApproval &&
            parkingLot.Status != ParkingLotStatus.Rejected)
        {
            throw new BadRequestException("Only pending or rejected parking lots can be approved.");
        }

        parkingLot.Status = ParkingLotStatus.Approved;
        parkingLot.IsActive = true;
        parkingLot.RejectReason = null;
        parkingLot.UpdatedAt = DateTime.UtcNow;
        parkingLot.UpdatedBy = adminId;

        await _parkingLotRepository.UpdateAsync(parkingLot, ct);
        return MapToResponseDto(parkingLot);
    }

    public async Task<ParkingLotResponseDto> RejectAsync(
        Guid parkingLotId,
        Guid adminId,
        string reason,
        CancellationToken ct = default)
    {
        var parkingLot = await _parkingLotRepository.GetByIdAsync(parkingLotId, includeDeleted: false, ct);
        if (parkingLot == null)
        {
            throw new NotFoundException(Messages.ParkingLot.NotFound);
        }

        parkingLot.Status = ParkingLotStatus.Rejected;
        parkingLot.IsActive = false;
        parkingLot.RejectReason = string.IsNullOrWhiteSpace(reason) ? null : reason.Trim();
        parkingLot.UpdatedAt = DateTime.UtcNow;
        parkingLot.UpdatedBy = adminId;

        await _parkingLotRepository.UpdateAsync(parkingLot, ct);
        return MapToResponseDto(parkingLot);
    }

    public async Task<IEnumerable<ParkingLotResponseDto>> GetNearbyAsync(
        decimal latitude,
        decimal longitude,
        decimal radiusKm,
        int maxResults,
        CancellationToken ct = default)
    {
        if (radiusKm <= 0)
        {
            throw new BadRequestException("radiusKm must be greater than 0.");
        }

        if (maxResults <= 0)
        {
            throw new BadRequestException("maxResults must be greater than 0.");
        }

        if (latitude is < -90 or > 90 || longitude is < -180 or > 180)
        {
            throw new BadRequestException("Invalid latitude/longitude values.");
        }

        var lots = await _parkingLotRepository.GetAllWithLocationAsync(onlyActive: true, ct);

        // Calculate distance (Haversine) in memory
        var originLat = (double)latitude;
        var originLng = (double)longitude;

        var results = lots
            .Select(lot =>
            {
                var distanceKm = lot.Latitude.HasValue && lot.Longitude.HasValue
                    ? CalculateDistanceKm(originLat, originLng, (double)lot.Latitude.Value, (double)lot.Longitude.Value)
                    : double.MaxValue;

                return new
                {
                    Lot = lot,
                    DistanceKm = distanceKm
                };
            })
            .Where(x => x.DistanceKm <= (double)radiusKm)
            .OrderBy(x => x.DistanceKm)
            .Take(maxResults)
            .ToList();

        return results.Select(x =>
        {
            var dto = MapToResponseDto(x.Lot);
            return dto with { DistanceKm = (decimal?)Math.Round(x.DistanceKm, 3) };
        });
    }

    private static ParkingLotResponseDto MapToResponseDto(ParkingLot parkingLot)
    {
        var availableCapacity = parkingLot.TotalCapacity - parkingLot.CurrentOccupancy;
        
        return new ParkingLotResponseDto(
            ParkingLotId: parkingLot.ParkingLotId,
            OwnerId: parkingLot.OwnerId,
            OwnerName: parkingLot.Owner?.FullName ?? "Unknown",
            Name: parkingLot.Name,
            Address: parkingLot.Address,
            Latitude: parkingLot.Latitude,
            Longitude: parkingLot.Longitude,
            DistanceKm: null,
            TotalCapacity: parkingLot.TotalCapacity,
            AvailableCapacity: availableCapacity > 0 ? availableCapacity : 0,
            CurrentOccupancy: parkingLot.CurrentOccupancy,
            PricePerHour: parkingLot.PricePerHour,
            Status: parkingLot.Status,
            IsActive: parkingLot.IsActive,
            RejectReason: parkingLot.RejectReason,
            ImageUrl: parkingLot.ImageUrl,
            CreatedAt: parkingLot.CreatedAt,
            UpdatedAt: parkingLot.UpdatedAt
        );
    }

    /// <summary>
    /// Calculates the great-circle distance between two points on the Earth using the Haversine formula.
    /// </summary>
    private static double CalculateDistanceKm(double lat1, double lon1, double lat2, double lon2)
    {
        const double EarthRadiusKm = 6371.0;

        double ToRadians(double angle) => Math.PI * angle / 180.0;

        var dLat = ToRadians(lat2 - lat1);
        var dLon = ToRadians(lon2 - lon1);

        var a = Math.Sin(dLat / 2) * Math.Sin(dLat / 2) +
                Math.Cos(ToRadians(lat1)) * Math.Cos(ToRadians(lat2)) *
                Math.Sin(dLon / 2) * Math.Sin(dLon / 2);

        var c = 2 * Math.Atan2(Math.Sqrt(a), Math.Sqrt(1 - a));

        return EarthRadiusKm * c;
    }
}
