// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class Booking
{
    public Guid BookingId { get; set; }

    public Guid UserId { get; set; }

    public Guid ParkingLotId { get; set; }

    public Guid? VehicleId { get; set; }

    public DateTime BookingTime { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Status { get; set; } = "Pending";

    public decimal TotalAmount { get; set; }

    // Check-in/Check-out timestamps
    public DateTime? CheckInTime { get; set; }

    public DateTime? CheckOutTime { get; set; }

    // Audit fields
    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    // Soft delete
    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public Guid? DeletedBy { get; set; }

    // Concurrency token
    public byte[] RowVersion { get; set; } = null!;

    // Navigation properties
    public virtual ParkingLot ParkingLot { get; set; } = null!;

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual User User { get; set; } = null!;

    public virtual Vehicle? Vehicle { get; set; }
}