// <auto-generated-like> Custom entity for owner upgrade flow. </auto-generated-like>
#nullable enable

using System;

namespace SmartParking.Domain.Entities;

public partial class OwnerUpgradeRequest
{
    public Guid RequestId { get; set; }

    public Guid UserId { get; set; }

    public string FullNameSnapshot { get; set; } = null!;

    public string EmailSnapshot { get; set; } = null!;

    public string? PhoneSnapshot { get; set; }

    public string ParkingLotName { get; set; } = null!;

    public string ParkingLotAddress { get; set; } = null!;

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    /// <summary>Optional image URL (from Cloudinary).</summary>
    public string? ImageUrl { get; set; }

    /// <summary>Optional description of the parking lot.</summary>
    public string? Description { get; set; }

    public string PlanType { get; set; } = null!;

    public decimal FeeAmount { get; set; }

    public string Status { get; set; } = null!;

    public string? RejectReason { get; set; }

    public Guid? PaymentTransactionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? RejectedAt { get; set; }

    public Guid? ProcessedBy { get; set; }

    public virtual User User { get; set; } = null!;
    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();
}

