// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class ParkingLot
{
    public Guid ParkingLotId { get; set; }

    public Guid OwnerId { get; set; }

    public string Name { get; set; } = null!;

    public string Address { get; set; } = null!;

    // Geolocation (for maps & navigation)
    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public int TotalCapacity { get; set; }

    public int CurrentOccupancy { get; set; }

    public decimal PricePerHour { get; set; }

    public string Status { get; set; } = "Active";
    
    public bool IsActive { get; set; } = true;

    // Audit fields
    public DateTime CreatedAt { get; set; }
    
    public DateTime? UpdatedAt { get; set; }
    
    public Guid? CreatedBy { get; set; }
    
    public Guid? UpdatedBy { get; set; }
    
    // Soft delete
    public bool IsDeleted { get; set; }
    
    public DateTime? DeletedAt { get; set; }
    
    public Guid? DeletedBy { get; set; }

    // Concurrency token
    public byte[] RowVersion { get; set; } = null!;

    // Navigation properties
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual User Owner { get; set; } = null!;
}