// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class ParkingLot
{
    public Guid ParkingLotId { get; set; }

    public Guid OwnerId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int TotalCapacity { get; set; }

    public int? CurrentOccupancy { get; set; }

    public decimal? PricePerHour { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual User Owner { get; set; }
}