// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class PaymentTransaction
{
    public Guid PaymentId { get; set; }

    public Guid? BookingId { get; set; }
    public Guid? OwnerUpgradeRequestId { get; set; }

    public Guid UserId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; } = "VNPay";

    public string PaymentStatus { get; set; } = "Pending";

    public string PaymentType { get; set; } = "Booking";

    public string VnpTxnRef { get; set; } = null!;

    public string? VnpTransactionNo { get; set; }

    public string? VnpResponseCode { get; set; }

    public string? VnpBankCode { get; set; }

    public string? VnpCardType { get; set; }

    // SePay fields
    public string? SePayOrderId { get; set; }

    public string? SePayTransactionId { get; set; }

    public string? SePayBankCode { get; set; }

    public string? SePayBankAccount { get; set; }

    public string? SePayTransferContent { get; set; }

    public string? SePayQrCode { get; set; }

    // Refund support
    public decimal? RefundAmount { get; set; }

    public string? RefundReason { get; set; }

    public DateTime? RefundedAt { get; set; }

    public Guid? RefundedBy { get; set; }

    // Metadata for additional data (JSON)
    public string? Metadata { get; set; }

    // Audit fields
    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    // Soft delete
    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public Guid? DeletedBy { get; set; }

    // Navigation properties
    public virtual Booking? Booking { get; set; }

    public virtual OwnerUpgradeRequest? OwnerUpgradeRequest { get; set; }

    public virtual ICollection<PaymentLog> PaymentLogs { get; set; } = new List<PaymentLog>();

    public virtual User User { get; set; } = null!;
}