// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class PaymentLog
{
    public Guid LogId { get; set; }

    public Guid PaymentId { get; set; }

    public string RawData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual PaymentTransaction Payment { get; set; }
}