// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class PaymentTransaction
{
    public Guid PaymentId { get; set; }

    public Guid BookingId { get; set; }

    public Guid UserId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string VnpTxnRef { get; set; }

    public string VnpTransactionNo { get; set; }

    public string VnpResponseCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<PaymentLog> PaymentLogs { get; set; } = new List<PaymentLog>();

    public virtual User User { get; set; }
}