// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartParking.Domain.Entities;

public partial class UserAuth
{
    public Guid AuthId { get; set; }

    public Guid UserId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}